version: '3.8'

services:
    web:
        build: .
        command: gunicorn shop_project.wsgi:application --bind 0.0.0.0:8000 --workers 4
        volumes:
            - .:/code
        ports:
            - "8000:8000"